Fix two bugs in WildShapeResizer (#981)
* Bump version to 0.0.2

* Convert to ES6 const/let declarations

* Use var to prevent ES6 from blowing up the initialization

ReferenceError: Cannot access 'WildShapeResizer' before initialization

* Prevent tokens from being resized to 0 when grid is disabled

* Fix image comparisons when tokens are copied.

The copied token uses the thumb url, rather than max.